apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: ebs-storage
        command: ["/bin/sh", "-c"]
        args: ["echo \"Current time: $(date)\" > /usr/share/nginx/html/time.txt && nginx -g 'daemon off;'"]
      volumes:
      - name: ebs-storage
        persistentVolumeClaim:
          claimName: pvc
