apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  fsType: ext4
